# -*- coding: utf-8 -*-
"""MLOM_Lab04A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9trwdzdI1jfRrIrnlV4KdSZadgfg6Ph
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import tensorflow as tf
from tensorflow import keras

data = pd.read_csv("diabetes.csv")
X = data.iloc[:, :8].values
y = data.iloc[:, 8].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Class counts: ", np.bincount(y))

X_train

X_test

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

X_train

X_test

model = keras.Sequential([
    keras.layers.Input(shape=(X_train.shape[1],)),
    keras.layers.Dense(5, activation="relu"),
    keras.layers.Dense(3, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")
])

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

history = model.fit(
  X_train, y_train,
  epochs=100,
  batch_size=32,
  validation_split=0.2,
  verbose=1
)

loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Accuracy: {acc:.4f}")

y_pred_prob = model.predict(X_test).ravel()
y_pred = (y_pred_prob >= 0.5).astype(int)
print(y_pred[:10])

print("First 10 predictions:", y_pred[:10])
print("First 10 actual labels:", y_test[:10])
print("Matches:", (y_pred[:10] == y_test[:10]).astype(int))

y_pred.shape

y_test.shape

