# -*- coding: utf-8 -*-
"""MLOM_Lab03A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vLij-hxwUAZG7zyFnlpRRvIew_BN4nvV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

boston = pd.read_csv("Boston.csv")
diabetes = pd.read_csv("diabetes.csv")

dfb = pd.DataFrame(boston)
dfd = pd.DataFrame(diabetes)

dfd.shape

dfd.head(3)

dfd.info()

x = dfd.iloc[:,:8]
y = dfd.iloc[:,8]

x.head(2)

y.head()

x.value_counts()

y.value_counts()

x.isnull().sum()

y.isnull().sum()

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

x_train.head()

x_test.head()

x_test.shape

y_test.shape

clf = MLPClassifier(alpha=0.01, hidden_layer_sizes=(5,3), random_state=1)

clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

accuracy_score(y_test,y_pred)

