# -*- coding: utf-8 -*-
"""Python_list_comprehensioin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLczgTjH5eD7WSglWjCVmx1pUkO-Qruo

# **List Comprehension**
"""

list = [x for x in range(1,11)]
list

doubles = [x*2 for x in list]
doubles

fruits = ["apples", "oranges", "mangoes", "berries", "bananas"]
fruits_in_capitals = [fruit.upper() for fruit in fruits]
fruits_in_capitals

"""### **Filter if**"""

fruits_back_in_simple = [fruit.lower() for fruit in fruits_in_capitals if fruit[0] not in ["A","E","I","O","U"]] # else isn't valid
fruits_back_in_simple

"""### **Conditional if else**"""

fruits_back_in_simple_but_all_elements = [fruit.lower() if fruit[0] not in ["A","E","I","O","U"] else fruit for fruit in fruits_in_capitals]
fruits_back_in_simple_but_all_elements

categories = [f"Even : {x+1}" if (x+1) % 2 == 0 else f"Odd : {x+1}" for x in range(10)]
categories

"""### **For Muti-Dimensional Lists**"""

matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

flattened = [num
             for row in matrix
             for num in row]
flattened

"""# **Dictionary Comprension**"""

pairs = [('a',1) , ('b',2), ('c',3)]
this_dict = {key:value for key,value in pairs}
this_dict

"""# **Set Comprehension**|"""

nums = [1,2,2,3,3,3,4,4,4,4]
uniq_sqrs = {x**2 for x in nums}
uniq_sqrs

"""# **Generator Comprehension**"""

sum_of_sqrs = sum(x**2 for x in range(1,10001))
sum_of_sqrs

"""# **Working with Dates**"""

from datetime import datetime
now = datetime.now()
now

print(f"{now:%x}")

print(f"{now:%c}")

print(f"{now:%H:%M:%S}")

