# -*- coding: utf-8 -*-
"""scikit-learn-scaling-&-standardization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfy7zgib34_oLA1cA02rSm-qp4rgMdZZ

# **General Stuff**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

df = load_iris(as_frame=True).frame

df.head(3)

df.columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "target"]

df.head(3)

X , y = df.iloc[:,:-1], df.iloc[:,-1]

X.head()

y.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

y_train.value_counts()

y_test.value_counts()

len(X_train), len(X_test)

train_counts = np.bincount(y_train)
train_classes = np.arange(len(train_counts))

plt.bar(train_classes, train_counts)

y_test.value_counts()

test_counts = np.bincount(y_test)
test_classes = np.arange(len(test_counts))
plt.bar(test_classes, test_counts)

X_train.hist(figsize=(14,8))

X_test.hist(figsize=(14,8))

"""# **Pre-Processing**"""

from sklearn.preprocessing import StandardScaler

df

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=20)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_train

X_man_scaled = (X_train - np.mean(X_train, axis=0)) / np.std(X_train,axis=0)
X_man_scaled.columns = ["sepal_length", "sepal_width", "petal_length", "petal_width"]
X_man_scaled

X_man_scaled.hist(figsize=(14,8))

